version: '3.7'

services:
  web:
    build: ./
    command: gunicorn main_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./m2m_express/:/usr/src/m2m_express/
    expose:
      - 8000
    env_file:
      - ./main_project/.env
#    depends_on:
#          - db
    links:
      - db
  db:
    image: postgres:12.0
    restart: 'always'
    env_file:
      - ./main_project/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=m2m_db
    ports:
    - 5432:5432

volumes:
  postgres_data:
