# Generated by Django 2.2 on 2021-01-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администраци'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='tel',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер телефона'),
        ),
    ]
