# Generated by Django 2.2 on 2021-01-11 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0002_auto_20210112_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 1, 2, 38, 228436), verbose_name='Дата создания'),
        ),
    ]
