# Generated by Django 2.2 on 2021-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0004_auto_20210112_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfileIndividualEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('ogrn', models.IntegerField(verbose_name='ОГРН')),
                ('kpp', models.IntegerField(verbose_name='КПП')),
                ('address', models.CharField(max_length=1000, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'ИП',
                'verbose_name_plural': 'ИП',
            },
        ),
        migrations.CreateModel(
            name='UsersProfileJuridical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('ogrn', models.IntegerField(verbose_name='ОГРН')),
                ('kpp', models.IntegerField(verbose_name='КПП')),
                ('address', models.CharField(max_length=1000, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридическое лицо',
            },
        ),
        migrations.CreateModel(
            name='UsersProfilePhysicalEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('tel', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('scan_copy', models.ImageField(unique=True, upload_to='scan_copy/', verbose_name='Освновное фото')),
            ],
            options={
                'verbose_name': 'Физическое Лицо',
                'verbose_name_plural': 'Физическое Лицо',
            },
        ),
    ]
