# Generated by Django 2.2 on 2021-01-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0005_usersprofileindividualentrepreneur_usersprofilejuridical_usersprofilephysicalentrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofileindividualentrepreneur',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_entrepreneur', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usersprofilejuridical',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juridical_entrepreneur', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usersprofilephysicalentrepreneur',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
