# Generated by Django 2.2 on 2021-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0007_auto_20210115_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofileindividualentrepreneur',
            name='inn',
            field=models.CharField(max_length=255, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='usersprofileindividualentrepreneur',
            name='kpp',
            field=models.CharField(max_length=255, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='usersprofileindividualentrepreneur',
            name='ogrn',
            field=models.CharField(max_length=255, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='usersprofilejuridical',
            name='inn',
            field=models.CharField(max_length=255, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='usersprofilejuridical',
            name='kpp',
            field=models.CharField(max_length=255, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='usersprofilejuridical',
            name='ogrn',
            field=models.CharField(max_length=255, verbose_name='ОГРН'),
        ),
    ]
