# Generated by Django 2.2 on 2021-01-22 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0008_auto_20210122_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofilephysicalentrepreneur',
            name='scan_copy_img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='scan_copy/img/', verbose_name='Скан фото'),
        ),
        migrations.AlterField(
            model_name='usersprofilephysicalentrepreneur',
            name='scan_copy_pdf',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='scan_copy/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Скфан pdf'),
        ),
    ]
