# Generated by Django 2.2 on 2021-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0011_tariff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен на странице'),
        ),
    ]
