# Generated by Django 2.2 on 2021-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0013_order_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='sdek_id',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Идентификатор отделения'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='usersprofileindividualentrepreneur',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='usersprofilejuridical',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_sdek',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Адресс СДЭК'),
        ),
    ]
