# Generated by Django 2.2 on 2021-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0015_order_custom_delivery_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('CUSTOM_TYPE', 'Custom'), ('STANDARD_TYPE', 'Standard')], default='STANDARD_TYPE', max_length=13, verbose_name='Тип доставки'),
        ),
    ]
