# Generated by Django 2.2 on 2021-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0017_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_sdek',
            field=models.CharField(default='-', max_length=1000, null=True, verbose_name='Адресс СДЭК'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='Трекинг номер'),
        ),
    ]
