# Generated by Django 2.2 on 2021-01-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0022_auto_20210131_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на страницу'),
        ),
    ]
