# Generated by Django 2.2 on 2021-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0024_auto_20210202_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_sdek',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True, verbose_name='Адресс СДЭК'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_delivery_message',
            field=models.CharField(blank=True, default=None, max_length=2056, null=True, verbose_name='Условия доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sdek_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Идентификатор отделения'),
        ),
    ]
