# Generated by Django 2.2 on 2021-02-04 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0027_auto_20210204_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('NOT_SELECTED', 'NOT SELECTED'), ('INVOICE', 'INVOICE'), ('BANK_CARD', 'BANK CARD')], default='NOT_SELECTED', max_length=63, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='usersprofilephysicalentrepreneur',
            name='scan_copy_img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='scan_copy/img/', verbose_name='Скан фото'),
        ),
        migrations.AlterField(
            model_name='usersprofilephysicalentrepreneur',
            name='scan_copy_pdf',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='scan_copy/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Скфан pdf'),
        ),
    ]
